name: rules
on:
  watch:
    types: started
# 定时触发编译
  schedule:
    - cron: 39 22 * * *
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: down mosdns
      run: |
        mkdir -p ./mosdns/amd64
        mkdir -p ./mosdns/arm64
        mkdir -p ./mosdns/mipsle
        wget -P /tmp  https://github.com/IrineSistiana/mosdns/releases/latest/download/mosdns-linux-amd64.zip
        unzip -o /tmp/mosdns-linux-amd64.zip -d ./mosdns/amd64
        rm -rf ./mosdns/amd64/README.md
        rm -rf ./mosdns/amd64/LICENSE
        rm -rf ./mosdns/amd64/config.yaml
        wget -P /tmp  https://github.com/IrineSistiana/mosdns/releases/latest/download/mosdns-linux-arm64.zip
        unzip -o /tmp/mosdns-linux-arm64.zip -d ./mosdns/arm64
        rm -rf ./mosdns/arm64/README.md
        rm -rf ./mosdns/arm64/LICENSE
        rm -rf ./mosdns/arm64/config.yaml
        wget -P /tmp  https://github.com/IrineSistiana/mosdns/releases/latest/download/mosdns-linux-mipsle-softfloat.zip
        unzip -o /tmp/mosdns-linux-mipsle-softfloat.zip -d ./mosdns/mipsle
        rm -rf ./mosdns/mipsle/README.md
        rm -rf ./mosdns/mipsle/LICENSE
        rm -rf ./mosdns/mipsle/config.yaml
    - name: down smartdns
      run: |
        mkdir -p ./smartdns
        wget -O ./smartdns/accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        sed -i "s|server=/top/114.114.114.114|#server=/top/114.114.114.114|" ./smartdns/accelerated-domains.china.conf
        sed -i "s|server=/|nameserver /|; s|/114.114.114.114|/china|" ./smartdns/accelerated-domains.china.conf
        sed -i '/#/d' ./smartdns/accelerated-domains.china.conf
        wget -O ./smartdns/apple.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
        sed -i "s|server=/|nameserver /|; s|/114.114.114.114|/china|" ./smartdns/apple.china.conf
        wget -O ./smartdns/google.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf
        sed -i "s|server=/|nameserver /|; s|/114.114.114.114|/china|" ./smartdns/google.china.conf
        wget -O ./smartdns/gfw.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
        sed -i "s/^/nameserver \//g;s/$/\/proxy/g" ./smartdns/gfw.txt
    - name: down cdns
      run: |
        mkdir -p ./cdns
        wget -O ./cdns/accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        sed -i "s|server=/top/114.114.114.114|#server=/top/114.114.114.114|" ./cdns/accelerated-domains.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./cdns/accelerated-domains.china.conf
        sed -i '/#/d' ./cdns/accelerated-domains.china.conf
        wget -O ./cdns/gfw.conf https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
        #sed -i "s/^/suffix:/g" ./cdns/gfw.conf
    - name: Install build dependencies
      run: |
        wget -O ./accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./accelerated-domains.china.conf
        sed -i '/#/d' ./accelerated-domains.china.conf
        sed -i '/top$/d' ./accelerated-domains.china.conf
        wget -O ./apple.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./apple.china.conf
        wget -O ./google.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./google.china.conf
        wget -O ./CN-ip-cidr.txt https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt
        sed -i '1d' ./CN-ip-cidr.txt
        wget -O ./gfw.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
        cat ./apple.china.conf ./google.china.conf > ./ecs_cn_domain.txt
        sed -i "s/^/full:/g" ./ecs_cn_domain.txt
        mkdir -p ./unbound
        cp ./accelerated-domains.china.conf ./unbound/accelerated-domains.china.unbound.conf
        sed -i 's|\(.*\)|forward-zone:\n  name: "\1."\n  forward-addr: 119.29.29.29\n|' ./unbound/accelerated-domains.china.unbound.conf
    - name: down switchsd
      run: |
        mkdir -p ./switchsd
        wget -O /tmp/atmosphere.zip https://github.com/Atmosphere-NX/Atmosphere/releases/download/1.6.2/atmosphere-1.6.2-master-f7bf379cf+hbl-2.4.4+hbmenu-3.6.0.zip
        wget -O /tmp/hekate.zip https://github.com/CTCaer/hekate/releases/download/v6.0.7/hekate_ctcaer_6.0.7_Nyx_1.5.6.zip
        unzip -o /tmp/atmosphere.zip -d ./switchsd
        unzip -o /tmp/hekate.zip -d ./switchsd
        wget -O ./switchsd/bootloader/payloads/fusee.bin https://github.com/Atmosphere-NX/Atmosphere/releases/latest/download/fusee.bin
        wget -O ./switchsd/switch/DBI/dbi.config  https://github.com/rashevskyv/dbi/releases/download/653/dbi.config
        mkdir -p ./switchsd/switch/DBI
        wget -O ./switchsd/switch/DBI/DBI.nro https://github.com/rashevskyv/dbi/releases/download/653/DBI.nro
        mkdir -p ./switchsd/switch/JKSV
        wget -O ./switchsd/switch/JKSV/JKSV.nro https://github.com/J-D-K/JKSV/releases/latest/download/JKSV.nro
        mkdir -p ./switchsd/switch/Goldleaf
        wget -O ./switchsd/switch/Goldleaf/Goldleaf.nro https://github.com/XorTroll/Goldleaf/releases/latest/download/Goldleaf.nro
        mkdir -p ./switchsd/switch/Amiigo
        wget -O ./switchsd/switch/Amiigo/Amiigo.nro https://github.com/CompSciOrBust/Amiigo/releases/latest/download/Amiigo.nro
        wget -O /tmp/linkalho.zip https://github.com/rdmrocha/linkalho/releases/download/v2.0.1/linkalho-v2.0.1.zip
        mkdir -p ./switchsd/switch/linkalho
        unzip -o /tmp/linkalho.zip -d ./switchsd/switch/linkalho
        mkdir -p ./switchsd/switch/appstore
        wget -O ./switchsd/switch/appstore/appstore.nro https://github.com/fortheusers/hb-appstore/releases/latest/download/appstore.nro
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am '.add'
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
