name: rules
on:
  workflow_dispatch:
# 定时触发编译
  schedule:
    - cron: 39 22 * * *
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        wget -O ./accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./accelerated-domains.china.conf
        wget -O ./apple.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./apple.china.conf
        wget -O ./google.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./google.china.conf
        wget -O ./CN-ip-cidr.txt https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt
        wget -O ./gfw.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am '.add'
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
