name: rules
on:
  watch:
    types: started
# 定时触发编译
  schedule:
    - cron: 39 22 * * *
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v4
    - name: Record time  
      run: echo `date` > ./date.log
    - name: down serv
      run: |
        mkdir -p ./m3u
        wget -O ./m3u/91.m3u http://serv.cloudns.be/91.m3u
        mkdir -p ./yaml
        wget -O ./yaml/fq.yaml http://serv.cloudns.be/yaml/fq.yaml
        wget -O ./yaml/steam.yaml http://serv.cloudns.be/yaml/steam.yaml
        wget -O ./yaml/Telegram.yaml http://serv.cloudns.be/yaml/Telegram.yaml
        wget -O ./yaml/google.yaml http://serv.cloudns.be/yaml/google.yaml
        wget -O ./yaml/zhilian.yaml http://serv.cloudns.be/yaml/zhilian.yaml
        wget -O ./yaml/BanAD.yaml http://serv.cloudns.be/yaml/BanAD.yaml
        wget -O ./yaml/netflix.yaml http://serv.cloudns.be/yaml/netflix.yaml
        wget -O ./yaml/windows.yaml http://serv.cloudns.be/yaml/windows.yaml
    - name: down smartdns
      run: |
        mkdir -p ./smartdns
        wget -O ./smartdns/accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        sed -i "s|server=/top/114.114.114.114|#server=/top/114.114.114.114|" ./smartdns/accelerated-domains.china.conf
        sed -i "s|server=/|nameserver /|; s|/114.114.114.114|/china|" ./smartdns/accelerated-domains.china.conf
        sed -i '/#/d' ./smartdns/accelerated-domains.china.conf
        wget -O ./smartdns/apple.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
        sed -i "s|server=/|nameserver /|; s|/114.114.114.114|/china|" ./smartdns/apple.china.conf
        wget -O ./smartdns/google.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf
        sed -i "s|server=/|nameserver /|; s|/114.114.114.114|/china|" ./smartdns/google.china.conf
        wget -O ./smartdns/gfw.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
        sed -i "s/^/nameserver \//g;s/$/\/proxy/g" ./smartdns/gfw.txt
    - name: down cdns
      run: |
        mkdir -p ./cdns
        wget -O ./cdns/accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        sed -i "s|server=/top/114.114.114.114|#server=/top/114.114.114.114|" ./cdns/accelerated-domains.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./cdns/accelerated-domains.china.conf
        sed -i '/#/d' ./cdns/accelerated-domains.china.conf
        wget -O ./cdns/gfw.conf https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
        #sed -i "s/^/suffix:/g" ./cdns/gfw.conf
    - name: Install build dependencies
      run: |
        wget -O ./accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        sed -i "s|server=/||; s|/114.114.114.114||" ./accelerated-domains.china.conf
        sed -i '/#/d' ./accelerated-domains.china.conf
        sed -i '/top$/d' ./accelerated-domains.china.conf
        wget -O ./CN-ip-cidr.txt https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt
        sed -i '1d' ./CN-ip-cidr.txt
        wget -O ./gfw.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
    - name: down switchsd
      run: |
        rm -rf ./switchsd
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -a -m "Add changes"
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
